/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DoubanAPITest;

import java.io.*;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import static io.restassured.RestAssured.*;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

import static org.hamcrest.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;
import static io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchemaInClasspath;

import com.tngtech.java.junit.dataprovider.DataProvider;
import com.tngtech.java.junit.dataprovider.DataProviderRunner;

import testData.EnvData;

public class AppTest {

    public String topFilm = "/v2/movie/top250";

    @Before
    public void setup(){
        baseURI = EnvData.doubanURL;
    }

//    @Test
//    public void testAppHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//    }

    @Test
    public void testDoubanApi() throws IOException{

        Response resp = given()
//                .header()
                .queryParam("start",'0')
                .queryParam("count",'1')
                .accept(ContentType.JSON)
                .when()
                .log().all()
                .get(topFilm)
                .then()
                .log().all()
                .assertThat()
                .statusCode(200)
                .extract().response();
//        MAP<String, String> cookie = resp.cookies();
//        System.out.print(cookie);
//        result = resp.body().toString();
//        System.out.println(result);

        int statusCode= resp.getStatusCode();
        writeFile(statusCode,topFilm);
    }

    public void writeFile(int statusCode, String caseUrl) throws IOException{

        FileWriter outFile = new FileWriter(EnvData.outoutFile);
        BufferedWriter output = new BufferedWriter(outFile);
        output.write(caseUrl+" 's statusCode is: "+statusCode);
        output.close();
    }

}
